# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^lib/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: ruff
        name: Lint Python with Ruff
        entry: uv run --frozen ruff check --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        args: [--fix, --config=pyproject.toml]
        require_serial: true
      - id: ruff-format
        name: Format Python with Ruff
        entry: uv run --frozen ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        args: [--config=pyproject.toml]
        require_serial: true
      - id: ty
        name: Type-check Python with ty
        entry: uv run --frozen ty check
        language: system
        types_or: [python, pyi, jupyter]
        pass_filenames: false
        always_run: true
        require_serial: true
